# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "43b68ab8ced50ea8c2f33b8097496c10"
name = "demo-app-project"
handle = "demo-app-project-3"
application_url = "https://sql-telephone-level-flying.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "book-shop312.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sql-telephone-level-flying.trycloudflare.com/auth/callback",
  "https://sql-telephone-level-flying.trycloudflare.com/auth/shopify/callback",
  "https://sql-telephone-level-flying.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
